### ISSUE TITLE
value request does not return results for value request if filter is empty 

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/ontology-driven-api#5]
http://vmdbpedia.informatik.uni-leipzig.de:8080/api/%201.0.0/values?entities=Barack_Obama&format=JSON&pretty=NONE&limit=1000&offset=0&key=1234&oldVersion=false

should return all properties and all of its corresponding values for the request
instead it does not return any result

**Comment by yum-yab** [comment]
There is a error in the URI, a space at the version, see *%20* in the URI.
The correct query without the space is working ([see here](http://vmdbpedia.informatik.uni-leipzig.de:8080/api/1.0.0/values?entities=Barack_Obama&format=JSON&pretty=NONE&limit=1000&offset=0&key=1234&oldVersion=false))
